apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wsrecaudos.fullname" . }}
  labels:
    {{- include "wsrecaudos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wsrecaudos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wsrecaudos.selectorLabels" . | nindent 8 }}
    spec:

      serviceAccountName: {{ .Values.serviceAccount.name }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      containers:
        - name: wsrecaudos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}