apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "serviceAccount.name is required" .Values.serviceAccount.name }}
  labels:
    {{- include "wsrecaudos.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}